---
title: Mediator
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: redcarpet
highlighter: pygments
gems:
- jemoji
description: 'A Jekyll theme - Medium inspired

'
email: a-mail@mail.mail
logo: "/assets/images/df_logo.jpg"
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"
name: Sam
author: Sameera
author_image: "/assets/images/author.jpeg"
paginate: 5
url: http://myblog.***.***
baseurl: ''
social:
- icon: twitter
  url: https://twitter.com/dirkfabisch
  desc: Follow me on twitter
  share_url: http://twitter.com/share
  share_title: "?text="
  share_link: "&amp;url="
- icon: github
  url: https://github.com/dirkfabisch
  desc: Fork me on github
  share_url: 
  share_title: 
  share_link: 
